version: 2.1

jobs:
  build:
    macos:
      xcode: "13.2.0"  # Adjust the Xcode version as needed
    steps:
      - checkout

      - run:
          name: Install dependencies
          command: |
            brew install cmake
            echo "CXX=clang++" >> $BASH_ENV

      - run:
          name: Setup SystemC
          command: |
            curl -LO https://github.com/accellera-official/systemc/archive/refs/tags/2.3.4.tar.gz
            tar -xzf 2.3.4.tar.gz
            mv systemc-2.3.4 systemc-2.3.4-source
            mkdir -p systemc-2.3.4-source/BUILD systemc-2.3.4-source/INSTALL
            cd systemc-2.3.4-source/BUILD
            cmake -DCMAKE_CXX_STANDARD=17 -DCMAKE_CXX_STANDARD_REQUIRED=ON -DCMAKE_INSTALL_PREFIX="../INSTALL" ..
            make -j$(sysctl -n hw.ncpu)
            make install
            cd ../..

      - run:
          name: Compile and Test C++ Modules
          command: |
            for file in *.cpp; do
              echo "Compiling and testing $file"
              g++ -std=c++17 -I systemc-2.3.4-source/INSTALL/include -L systemc-2.3.4-source/INSTALL/lib -lsystemc "$file" -o "${file%.cpp}"
              ./${file%.cpp}
            done

workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          filters:
            branches:
              only: main  # This runs the job only for commits on the "main" branch.
